// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj27a9hBzbOpiau9GOu1l43rMldcSy_YY',
    appId: '1:374945143785:web:e22b55ba4b55cb2f938978',
    messagingSenderId: '374945143785',
    projectId: 'shopapp-getx-firebase',
    authDomain: 'shopapp-getx-firebase.firebaseapp.com',
    storageBucket: 'shopapp-getx-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJA5Dd0rzYngIeiw8aP_xxoD7-z6zitU',
    appId: '1:374945143785:android:140a70eb42949a53938978',
    messagingSenderId: '374945143785',
    projectId: 'shopapp-getx-firebase',
    storageBucket: 'shopapp-getx-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjE50cn_2Pz_8dMwqmsRhCAPYBtJJ_MSk',
    appId: '1:374945143785:ios:19f8b522f8eea1ce938978',
    messagingSenderId: '374945143785',
    projectId: 'shopapp-getx-firebase',
    storageBucket: 'shopapp-getx-firebase.appspot.com',
    iosClientId: '374945143785-9od66eg96kumhgh7oqt3rsaulul9k6ad.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopGetxFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjE50cn_2Pz_8dMwqmsRhCAPYBtJJ_MSk',
    appId: '1:374945143785:ios:19f8b522f8eea1ce938978',
    messagingSenderId: '374945143785',
    projectId: 'shopapp-getx-firebase',
    storageBucket: 'shopapp-getx-firebase.appspot.com',
    iosClientId: '374945143785-9od66eg96kumhgh7oqt3rsaulul9k6ad.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopGetxFirebase',
  );
}
